services:
  app:
    build: .
    container_name: cliente_notifier
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./UsersIPTV.xlsx:/app/UsersIPTV.xlsx
